# Generated by Django 2.1 on 2018-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(upload_to='blog/pictures/')),
            ],
        ),
    ]
